name: Node.js CD
 
on:
  push:
    branches: [ main ]
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd bcsbot
            git pull
            npm install
            screen -X -S 'bcs_bot' quit && echo 'Succesfully deleted last session.'
            bash start.sh && echo 'Started new session.'